from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot Quamba Figure-3-style 3D sorted activation surface from profile_tensors.pt.")
    parser.add_argument("--profile", required=True, help="Path to profile_tensors.pt generated by plot_quamba_outlier_profile.py.")
    parser.add_argument("--output-root", required=True)
    parser.add_argument("--dim-points", type=int, default=512, help="Number of sorted channels to render along the Dims axis.")
    parser.add_argument("--token-points", type=int, default=256, help="Number of tokens to render along the Token axis.")
    parser.add_argument("--z-clip-quantile", type=float, default=0.999, help="Clip z/color range for readable spikes.")
    parser.add_argument("--view-elev", type=float, default=28.0)
    parser.add_argument("--view-azim", type=float, default=-58.0)
    args = parser.parse_args()

    profile_path = Path(args.profile)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    payload = torch.load(profile_path, map_location="cpu")
    x_channel_max = payload["x_channel_max"].float().abs()
    x = payload["online"]["x"].float().abs()
    if x.ndim != 2:
        raise ValueError(f"Expected online x to be [token, dim], got {tuple(x.shape)}")

    sorted_idx = torch.argsort(x_channel_max, descending=True)
    x_sorted = x[:, sorted_idx]
    seqlen, ndim = x_sorted.shape

    token_step = max(1, seqlen // args.token_points)
    dim_step = max(1, ndim // args.dim_points)
    token_idx = torch.arange(0, seqlen, token_step)[: args.token_points]
    dim_idx = torch.arange(0, ndim, dim_step)[: args.dim_points]
    z = x_sorted.index_select(0, token_idx).index_select(1, dim_idx)

    z_clip = float(torch.quantile(z.reshape(-1), args.z_clip_quantile))
    z_plot = z.clamp_max(z_clip)
    token_grid, dim_grid = torch.meshgrid(token_idx.float(), dim_idx.float(), indexing="ij")

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib import cm
    from matplotlib.colors import Normalize

    fig = plt.figure(figsize=(9.2, 7.2), constrained_layout=True)
    ax = fig.add_subplot(111, projection="3d")
    norm = Normalize(vmin=0.0, vmax=max(z_clip, 1e-12))
    colors = cm.coolwarm(norm(z_plot.numpy()))
    ax.plot_surface(
        token_grid.numpy(),
        dim_grid.numpy(),
        z_plot.numpy(),
        facecolors=colors,
        rstride=1,
        cstride=1,
        linewidth=0,
        antialiased=False,
        shade=False,
    )
    ax.set_title("Sorted x activation")
    ax.set_xlabel("Token")
    ax.set_ylabel("Dims")
    ax.set_zlabel("|activation|")
    ax.set_xlim(float(token_idx.min()), float(token_idx.max()))
    ax.set_ylim(float(dim_idx.min()), float(dim_idx.max()))
    ax.set_zlim(0.0, max(z_clip, 1e-12))
    ax.view_init(elev=args.view_elev, azim=args.view_azim)
    mappable = cm.ScalarMappable(norm=norm, cmap=cm.coolwarm)
    mappable.set_array([])
    fig.colorbar(mappable, ax=ax, shrink=0.7, pad=0.08, label="|activation|")
    fig.savefig(output_root / "figure3a_sorted_x_activation_3d.png", dpi=240)
    plt.close(fig)

    torch.save(
        {
            "token_idx": token_idx,
            "dim_idx": dim_idx,
            "z_abs_activation": z,
            "z_clipped": z_plot,
            "sorted_channel_idx": sorted_idx,
        },
        output_root / "figure3a_sorted_x_activation_3d_data.pt",
    )
    (output_root / "figure3a_sorted_x_activation_3d_meta.json").write_text(
        json.dumps(
            {
                "profile": str(profile_path),
                "output_root": str(output_root),
                "source_shape": [seqlen, ndim],
                "render_shape": list(z.shape),
                "dim_points": int(len(dim_idx)),
                "token_points": int(len(token_idx)),
                "z_clip_quantile": args.z_clip_quantile,
                "z_clip": z_clip,
                "z_raw_max": float(z.max()),
                "z_raw_p99": float(torch.quantile(z.reshape(-1), 0.99)),
                "sort": "x_channel_max descending",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(json.dumps({"event": "done", "output_root": str(output_root), "z_clip": z_clip}), flush=True)


if __name__ == "__main__":
    main()
