from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

import torch


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    columns: list[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def pca_3d(features: torch.Tensor) -> torch.Tensor:
    centered = features - features.mean(dim=0, keepdim=True)
    _, _, vh = torch.linalg.svd(centered, full_matrices=False)
    return centered @ vh[:3].T


def tsne_3d(features: torch.Tensor, perplexity: float, seed: int) -> torch.Tensor:
    from sklearn.manifold import TSNE

    n = features.shape[0]
    perplexity = min(perplexity, max(2.0, (n - 1) / 3))
    tsne = TSNE(
        n_components=3,
        perplexity=perplexity,
        init="pca",
        learning_rate="auto",
        metric="euclidean",
        random_state=seed,
    )
    coords = tsne.fit_transform(features.numpy())
    return torch.from_numpy(coords).float()


def cluster_heads(features: torch.Tensor, ngroups: int, heads_per_group: int, nhead_groups: int) -> torch.Tensor:
    try:
        from sklearn.cluster import AgglomerativeClustering
    except Exception:
        return torch.zeros((ngroups, heads_per_group), dtype=torch.long)

    labels = torch.empty((ngroups, heads_per_group), dtype=torch.long)
    grouped = features.reshape(ngroups, heads_per_group, -1).numpy()
    for group_idx in range(ngroups):
        n_clusters = min(nhead_groups, heads_per_group)
        clustering = AgglomerativeClustering(n_clusters=n_clusters, metric="euclidean", linkage="ward")
        labels[group_idx] = torch.from_numpy(clustering.fit_predict(grouped[group_idx])).long()
    return labels


def plot_3d(
    output_path: Path,
    coords: torch.Tensor,
    rows: list[dict[str, Any]],
    *,
    title: str,
    color_key: str,
    cmap: str,
) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    values = torch.tensor([int(row[color_key]) for row in rows])
    fig = plt.figure(figsize=(8.5, 7.5), constrained_layout=True)
    ax = fig.add_subplot(111, projection="3d")
    scatter = ax.scatter(
        coords[:, 0].numpy(),
        coords[:, 1].numpy(),
        coords[:, 2].numpy(),
        c=values.numpy(),
        cmap=cmap,
        s=44,
        alpha=0.88,
        edgecolors="black",
        linewidths=0.25,
    )
    ax.set_title(title)
    ax.set_xlabel("dim 1")
    ax.set_ylabel("dim 2")
    ax.set_zlabel("dim 3")
    cbar = fig.colorbar(scatter, ax=ax, shrink=0.7, pad=0.08)
    cbar.set_label(color_key.replace("_", " "))
    ax.view_init(elev=22, azim=38)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=240)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot Quamba2-style 3D head-profile coordinates from saved profile_tensors.pt.")
    parser.add_argument("--profile", required=True, help="Path to profile_tensors.pt generated by plot_quamba_outlier_profile.py.")
    parser.add_argument("--output-root", default=None)
    parser.add_argument("--headdim", type=int, default=None)
    parser.add_argument("--ngroups", type=int, default=None)
    parser.add_argument("--nhead-groups", type=int, default=4)
    parser.add_argument("--perplexity", type=float, default=20.0)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    profile_path = Path(args.profile)
    output_root = Path(args.output_root) if args.output_root else profile_path.parent
    payload = torch.load(profile_path, map_location="cpu")
    x_max = payload["x_channel_max"].float().abs()

    meta_path = profile_path.parent / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    headdim = int(args.headdim or meta.get("headdim") or 64)
    ngroups = int(args.ngroups or meta.get("ngroups") or 1)
    if x_max.numel() % (ngroups * headdim) != 0:
        raise ValueError(f"x_channel_max length {x_max.numel()} is not divisible by ngroups*headdim={ngroups * headdim}")

    heads_per_group = x_max.numel() // (ngroups * headdim)
    head_profiles = x_max.reshape(ngroups, heads_per_group, headdim)
    sorted_profiles = torch.sort(head_profiles, dim=-1).values
    features = sorted_profiles.reshape(ngroups * heads_per_group, headdim)
    features = features / features.norm(dim=-1, keepdim=True).clamp_min(1e-12)

    cluster_labels = cluster_heads(features, ngroups, heads_per_group, args.nhead_groups).reshape(-1)
    pca_coords = pca_3d(features)
    method = "tsne"
    try:
        coords = tsne_3d(features, args.perplexity, args.seed)
    except Exception:
        coords = pca_coords
        method = "pca_fallback"

    rows = []
    flat_profiles = head_profiles.reshape(ngroups * heads_per_group, headdim)
    for flat_idx in range(features.shape[0]):
        group_idx = flat_idx // heads_per_group
        head_idx = flat_idx % heads_per_group
        rows.append(
            {
                "flat_head": flat_idx,
                "ssd_group": group_idx,
                "head_in_group": head_idx,
                "cluster": int(cluster_labels[flat_idx]),
                "coord_x": float(coords[flat_idx, 0]),
                "coord_y": float(coords[flat_idx, 1]),
                "coord_z": float(coords[flat_idx, 2]),
                "pca_x": float(pca_coords[flat_idx, 0]),
                "pca_y": float(pca_coords[flat_idx, 1]),
                "pca_z": float(pca_coords[flat_idx, 2]),
                "profile_max": float(flat_profiles[flat_idx].max()),
                "profile_mean": float(flat_profiles[flat_idx].mean()),
            }
        )

    write_csv(output_root / "figure4_head_profile_3d_coords.csv", rows)
    title_base = f"Layer {meta.get('layer_idx', 'unknown')} head profile 3D"
    plot_3d(
        output_root / "figure4_head_profile_3d_by_group.png",
        coords,
        rows,
        title=f"{title_base} ({method}, colored by SSD group)",
        color_key="ssd_group",
        cmap="tab10",
    )
    plot_3d(
        output_root / "figure4_head_profile_3d_by_cluster.png",
        coords,
        rows,
        title=f"{title_base} ({method}, colored by head cluster)",
        color_key="cluster",
        cmap="Set2",
    )
    plot_3d(
        output_root / "figure4_head_profile_3d_pca_by_group.png",
        pca_coords,
        rows,
        title=f"{title_base} (PCA, colored by SSD group)",
        color_key="ssd_group",
        cmap="tab10",
    )
    (output_root / "figure4_head_profile_3d_meta.json").write_text(
        json.dumps(
            {
                "profile": str(profile_path),
                "output_root": str(output_root),
                "method": method,
                "ngroups": ngroups,
                "heads_per_group": heads_per_group,
                "headdim": headdim,
                "nhead_groups": args.nhead_groups,
                "perplexity": args.perplexity,
                "seed": args.seed,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(json.dumps({"event": "done", "output_root": str(output_root), "method": method}), flush=True)


if __name__ == "__main__":
    main()
