from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch


def sample_sorted_activation(
    activation: torch.Tensor,
    sorted_idx: torch.Tensor,
    token_idx: torch.Tensor,
    dim_idx: torch.Tensor,
) -> torch.Tensor:
    return activation[:, sorted_idx].index_select(0, token_idx).index_select(1, dim_idx)


def plot_surface(
    ax,
    token_grid: torch.Tensor,
    dim_grid: torch.Tensor,
    z: torch.Tensor,
    *,
    z_clip: float,
    title: str,
    view_elev: float,
    view_azim: float,
):
    from matplotlib import cm
    from matplotlib.colors import Normalize

    z_plot = z.clamp_max(z_clip)
    norm = Normalize(vmin=0.0, vmax=max(z_clip, 1e-12))
    colors = cm.coolwarm(norm(z_plot.numpy()))
    ax.plot_surface(
        token_grid.numpy(),
        dim_grid.numpy(),
        z_plot.numpy(),
        facecolors=colors,
        rstride=1,
        cstride=1,
        linewidth=0,
        antialiased=False,
        shade=False,
    )
    ax.set_title(title)
    ax.set_xlabel("Token")
    ax.set_ylabel("Dims")
    ax.set_zlabel("|activation|")
    ax.set_xlim(float(token_grid.min()), float(token_grid.max()))
    ax.set_ylim(float(dim_grid.max()), float(dim_grid.min()))
    ax.set_zlim(0.0, max(z_clip, 1e-12))
    ax.view_init(elev=view_elev, azim=view_azim)
    mappable = cm.ScalarMappable(norm=norm, cmap=cm.coolwarm)
    mappable.set_array([])
    return mappable


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot Quamba Figure-3-style 3D sorted activation surface from profile_tensors.pt.")
    parser.add_argument("--profile", required=True, help="Path to profile_tensors.pt generated by plot_quamba_outlier_profile.py.")
    parser.add_argument("--output-root", required=True)
    parser.add_argument("--dim-points", type=int, default=512, help="Number of sorted channels to render along the Dims axis.")
    parser.add_argument("--token-points", type=int, default=256, help="Number of tokens to render along the Token axis.")
    parser.add_argument("--z-clip-quantile", type=float, default=0.999, help="Clip z/color range for readable spikes.")
    parser.add_argument("--view-elev", type=float, default=28.0)
    parser.add_argument("--view-azim", type=float, default=-58.0)
    args = parser.parse_args()

    profile_path = Path(args.profile)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    payload = torch.load(profile_path, map_location="cpu")
    x_channel_max = payload["x_channel_max"].float().abs()
    x = payload["online"]["x"].float().abs()
    y = payload["online"]["y"].float().abs()
    if x.ndim != 2:
        raise ValueError(f"Expected online x to be [token, dim], got {tuple(x.shape)}")
    if y.shape != x.shape:
        raise ValueError(f"Expected online y shape to match x, got x={tuple(x.shape)} y={tuple(y.shape)}")

    sorted_idx = torch.argsort(x_channel_max, descending=True)
    seqlen, ndim = x.shape

    token_step = max(1, seqlen // args.token_points)
    dim_step = max(1, ndim // args.dim_points)
    token_idx = torch.arange(0, seqlen, token_step)[: args.token_points]
    dim_idx = torch.arange(0, ndim, dim_step)[: args.dim_points]
    x_z = sample_sorted_activation(x, sorted_idx, token_idx, dim_idx)
    y_z = sample_sorted_activation(y, sorted_idx, token_idx, dim_idx)

    x_z_clip = float(torch.quantile(x_z.reshape(-1), args.z_clip_quantile))
    y_z_clip = float(torch.quantile(y_z.reshape(-1), args.z_clip_quantile))
    token_grid, dim_grid = torch.meshgrid(token_idx.float(), dim_idx.float(), indexing="ij")

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(9.2, 7.2), constrained_layout=True)
    ax = fig.add_subplot(111, projection="3d")
    x_mappable = plot_surface(
        ax,
        token_grid,
        dim_grid,
        x_z,
        z_clip=x_z_clip,
        title="Sorted x activation",
        view_elev=args.view_elev,
        view_azim=args.view_azim,
    )
    fig.colorbar(x_mappable, ax=ax, shrink=0.7, pad=0.08, label="|x activation|")
    fig.savefig(output_root / "figure3a_sorted_x_activation_3d.png", dpi=240)
    plt.close(fig)

    fig = plt.figure(figsize=(16.5, 7.2), constrained_layout=True)
    ax_x = fig.add_subplot(121, projection="3d")
    ax_y = fig.add_subplot(122, projection="3d")
    x_mappable = plot_surface(
        ax_x,
        token_grid,
        dim_grid,
        x_z,
        z_clip=x_z_clip,
        title="(a) Sorted x activation",
        view_elev=args.view_elev,
        view_azim=args.view_azim,
    )
    y_mappable = plot_surface(
        ax_y,
        token_grid,
        dim_grid,
        y_z,
        z_clip=y_z_clip,
        title="(b) Sorted y activation",
        view_elev=args.view_elev,
        view_azim=args.view_azim,
    )
    fig.colorbar(x_mappable, ax=ax_x, shrink=0.68, pad=0.08, label="|x activation|")
    fig.colorbar(y_mappable, ax=ax_y, shrink=0.68, pad=0.08, label="|y activation|")
    fig.savefig(output_root / "figure3_sorted_x_y_activation_3d.png", dpi=240)
    plt.close(fig)

    torch.save(
        {
            "token_idx": token_idx,
            "dim_idx": dim_idx,
            "x_abs_activation": x_z,
            "y_abs_activation": y_z,
            "x_clipped": x_z.clamp_max(x_z_clip),
            "y_clipped": y_z.clamp_max(y_z_clip),
            "sorted_channel_idx": sorted_idx,
        },
        output_root / "figure3a_sorted_x_activation_3d_data.pt",
    )
    (output_root / "figure3a_sorted_x_activation_3d_meta.json").write_text(
        json.dumps(
            {
                "profile": str(profile_path),
                "output_root": str(output_root),
                "source_shape": [seqlen, ndim],
                "render_shape": list(z.shape),
                "dim_points": int(len(dim_idx)),
                "token_points": int(len(token_idx)),
                "z_clip_quantile": args.z_clip_quantile,
                "x_z_clip": x_z_clip,
                "y_z_clip": y_z_clip,
                "x_raw_max": float(x_z.max()),
                "y_raw_max": float(y_z.max()),
                "x_raw_p99": float(torch.quantile(x_z.reshape(-1), 0.99)),
                "y_raw_p99": float(torch.quantile(y_z.reshape(-1), 0.99)),
                "sort": "x_channel_max descending",
                "dims_axis": "displayed high-to-low to keep low-activation channels visible",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(json.dumps({"event": "done", "output_root": str(output_root), "x_z_clip": x_z_clip, "y_z_clip": y_z_clip}), flush=True)


if __name__ == "__main__":
    main()
